title: MUSA 550
logo: /assets/img/logo.jpg
description: Heat Island Explore in Philly
show_downloads: false
repository: MUSA-550-Fall-2021/final-project-hui_shimin
google_analytics:
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
